[2023-04-26T08:47:47.376+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-04-26T08:47:45.492178+00:00 [queued]>
[2023-04-26T08:47:47.382+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-04-26T08:47:45.492178+00:00 [queued]>
[2023-04-26T08:47:47.383+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T08:47:47.383+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-04-26T08:47:47.384+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-04-26T08:47:47.391+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-04-26 08:47:45.492178+00:00
[2023-04-26T08:47:47.396+0000] {standard_task_runner.py:55} INFO - Started process 928 to run task
[2023-04-26T08:47:47.400+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-04-26T08:47:45.492178+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpg3q3u9z0']
[2023-04-26T08:47:47.402+0000] {standard_task_runner.py:83} INFO - Job 214: Subtask is_api_available
[2023-04-26T08:47:47.452+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-04-26T08:47:45.492178+00:00 [running]> on host c452347a64f2
[2023-04-26T08:47:47.502+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-04-26T08:47:45.492178+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-26T08:47:45.492178+00:00
[2023-04-26T08:47:47.503+0000] {http.py:120} INFO - Poking: api/
[2023-04-26T08:47:47.513+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-04-26T08:47:47.515+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-04-26T08:47:48.658+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-04-26T08:47:48.686+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230426T084745, start_date=20230426T084747, end_date=20230426T084748
[2023-04-26T08:47:48.733+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-04-26T08:47:48.764+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
